GRANT USAGE ON SCHEMA schema_name TO role_name;
GRANT SELECT ON ALL TABLES IN SCHEMA schema_name TO role_name;

REVOKE SELECT ON table_name FROM role_name;

REVOKE USAGE ON SCHEMA schema_name FROM role_name;


-- drop column 
ALTER TABLE table_name DROP COLUMN column_name;


GRANT USAGE ON SCHEMA backend TO bi;
GRANT SELECT ON ALL TABLES IN SCHEMA backend TO bi;

GRANT USAGE ON SCHEMA ios TO bi;
GRANT SELECT ON ALL TABLES IN SCHEMA ios TO bi;

GRANT USAGE ON SCHEMA android TO bi;
GRANT SELECT ON ALL TABLES IN SCHEMA android TO bi;

GRANT USAGE ON SCHEMA javascript TO bi;
GRANT SELECT ON ALL TABLES IN SCHEMA javascript TO bi;
